version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint-django.sh
    env_file:
      - .env
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ENV=${DJANGO_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - GMAIL_API_CLIENT_ID=${GMAIL_API_CLIENT_ID}
      - GMAIL_API_CLIENT_SECRET=${GMAIL_API_CLIENT_SECRET}
      - GMAIL_API_REFRESH_TOKEN=${GMAIL_API_REFRESH_TOKEN}

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /home/dev/myproject/react-app/build:/usr/share/nginx/html:ro
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app 
    depends_on:
      - db
      - redis
    command: ./entrypoint-celery.sh
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ENV=${DJANGO_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - GMAIL_API_CLIENT_ID=${GMAIL_API_CLIENT_ID}
      - GMAIL_API_CLIENT_SECRET=${GMAIL_API_CLIENT_SECRET}
      - GMAIL_API_REFRESH_TOKEN=${GMAIL_API_REFRESH_TOKEN}

  flower:
    build: .
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - celery
    command: celery -A graduation_backend flower --port=5555
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ENV=${DJANGO_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - GMAIL_API_CLIENT_ID=${GMAIL_API_CLIENT_ID}
      - GMAIL_API_CLIENT_SECRET=${GMAIL_API_CLIENT_SECRET}
      - GMAIL_API_REFRESH_TOKEN=${GMAIL_API_REFRESH_TOKEN}

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
